export const refs = {
  movies: document.querySelector('#movies'),
  containerFilm: document.querySelector('#container-film'),
  filmList: document.querySelector('.film__list'),
  searchForm: document.querySelector('.header__form'),
  headerSearchBlock: document.querySelector('.header__form--visibel'),
  headerFailureNotice: document.querySelector('.header__notice'),
  headerLibraryButtons: document.querySelector('.header__block--button'),
  libraryLink: document.querySelector('.js-library'),
  homeLink: document.querySelector('.js-home'),
  header: document.querySelector('.header'),
  btnWatched: document.querySelector('.js-watched'),
  btnQueue: document.querySelector('.js-queue'),
  pagination: document.querySelector('.js-pagination'),
  logo: document.querySelector('.header__logo'),
  iconDark: document.querySelector('#moon'),
  iconLight: document.querySelector('#sun'),
  body: document.querySelector('body'),
};
